# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Post.destroy_all
User.destroy_all
Reply.destroy_all


@file = Rack::Test::UploadedFile.new(Rails.root + 'james.jpg', 'image/jpg')

%w(jim jam jom).each do |name|
  email = "#{name}@example.com"
  username = "#{name}my #{name}z"
  # next if jumps to the next iteration if the condition is true.
  # this code prevents duplicate emails from being created
  next if User.exists? email: email
  User.create!(
    full_name: username,
    username: username,
    email: email,
    password: 'password',
    # if any value of password_confirmation other than nil exists, it MUST match password. nill just ignores the confirmation
    password_confirmation: nil)
  # password: and password_confirmation: are VIRTUAL ATTRIBUTES generated by has_secure_password
end

jim = User.first.id
jam = User.second.id
jom = User.third.id

Post.create!(title:"test post please ignore.", body:"Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and", post_image: @file, user_id: jom )



Post.create!(title:"a post on this blog here!", body:"c quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus var", start_date:"06/05/2015", end_date:"07/07/2015", user_id:jim)
