# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Post.destroy_all
User.destroy_all


@file = Rack::Test::UploadedFile.new(Rails.root + 'james.jpg', 'image/jpg')

Post.create!(post_image: @file)


%w(jim jam jom).each do |name|
  email = "#{name}@example.com"
  # next if jumps to the next iteration if the condition is true.
  # this code prevents duplicate emails from being created
  next if User.exists? email: email
  User.create!(email: email,
              password: 'password',
              # if any value of password_confirmation other than nil exists, it MUST match password. nill just ignores the confirmation
              password_confirmation: nil)
  # password: and password_confirmation: are VIRTUAL ATTRIBUTES generated by has_secure_password
end
